import Footer from "@/components/footer/Footer";
// import ResponsiveTester from "@/lib/ResponsiveTester";
import "@/styles/globals.css";

import { type Metadata } from "next";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  // preload: true,
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Umar Interview",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${poppins.variable} ${poppins.className}`}>
      <body>
        <div className="font-poppins relative h-full antialiased">
          <main className="relative flex min-h-screen flex-col">
            <div className="flex-1 flex-grow">{children}</div>
            <Footer />
          </main>
        </div>
        {/* <ResponsiveTester /> */}
      </body>
    </html>
  );
}
